spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dc
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: delivery-service
server:
  port: 8080
  servlet:
    context-path: /delivery-service
